In [69]:
import pandas as pd
df = pd.read_parquet("../data/processed/results.parquet")

# Harmonisation des catégories

In [70]:
df["Categorie"].unique()

<ArrowStringArray>
[  'SEN',   'VE2',   'VE1',   'ESP',   'VE3',   'DAM',   'AI2',   'AI1',
   'VE4',   'XXX',   'AI3',   'ESF',   'SEH',   'ESH',   'V1H',   'V1F',
   'SEF',   'V3F',   'V2F',    'JH',    'JF',    'SH',    'V1',    'V2',
    'SD',    'V3',    'A1',    'A2',    'V4',    'A3',    'V5',    'A4',
   'V2H',   'V3H',   'V4H',    'SE',    'EH',    'DA',    'EF',   'xxx',
   'JUH',   'JUF',     'H',     'F',     '0',    'ED',   'AI4',      '',
   'GAR',   'FIL',  '#N/A', '#REF!',   'V4F',  'DISH',  'DISF']
Length: 55, dtype: str

In [71]:
# dictionnaire d'harmonisation
mapping = {
    # catégories invalides
    '': 'XXX',
    '#N/A': 'XXX',
    '#REF!': 'XXX',
    'xxx': 'XXX',
    'XXX': 'XXX',
    '0': 'XXX',

    # A1
    'A1': 'A1',
    'AI1': 'A1',
    'V1F': 'A1',

    # A2
    'A2': 'A2',
    'AI2': 'A2',
    'V2F': 'A2',

    # A3
    'A3': 'A3',
    'AI3': 'A3',
    'V3F': 'A3',

    # A4
    'A4': 'A4',
    'AI4': 'A4',
    'V4F': 'A4',

    # A5
    'A5': 'A5',
    'AI5': 'A5',
    'V45': 'A5',

    # SH
    'SH': 'SH',
    'H': 'SH',
    'SEH': 'SH',
    'SEN': 'SH',
    'DISH': 'SH',
    'SE': 'SH',

    #ESH
    'JUH': 'ESH',
    'JH': 'ESH',
    'EH': 'ESH',
    'ESH': 'ESH',
    'ESP': 'ESH',
    'GAR': 'ESH',

    # SD
    'DA': 'SD',
    'DAM': 'SD',
    'SD': 'SD',
    'F': 'SD',
    'SEF': 'SD',
    'DISF': 'SD',

    #ESF
    'JUF': 'ESF',
    'JF': 'ESF',
    'EF': 'ESF',
    'ESF': 'ESF',
    'FIL': 'ESF',
    'ED': 'ESF',

    # V1
    'V1': 'V1',
    'VE1': 'V1',
    'V1H': 'V1',

    # V2
    'V2': 'V2',
    'VE2': 'V2',
    'V2H': 'V2',

    # V3
    'V3': 'V3',
    'VE3': 'V3',
    'V3H': 'V3',

    # V4
    'V4': 'V4',
    'VE4': 'V4',
    'V4H': 'V4',

    # V5
    'V5': 'V5',
    'VE5': 'V5',
    'V5H': 'V5',
}

# harmonisation
df['categorie_harmonisee'] = (
    df['Categorie']
    .map(mapping)
    .fillna('XXX')
)

print(df['categorie_harmonisee'].unique())

<ArrowStringArray>
[ 'SH',  'V2',  'V1', 'ESH',  'V3',  'SD',  'A2',  'A1',  'V4', 'XXX',  'A3',
 'ESF',  'V5',  'A4']
Length: 14, dtype: str

# Correction des entrées erronées pour le sexe

In [72]:
df[~df["Sexe"].isin(["H", "F", "X"])]

,Position,Nom,Club,Sexe,Categorie,Position Catégorie,Temps,NomCourse,Date,Distance,source_file,racekey,categorie_harmonisee
89253,254,2264 N.N.,,,,1,03:14:35,La Clavieroise,2025-06-08,6.23,20250806ClavierPC.pdf,la clavieroise_2025-06-08_6.23,XXX
96838,243,Mergeai Agnes,F Neuf Moulin,F NEUF MOULIN,A3,6,01:01:09,Le Jog&Trail De Villers-Le-Temple,2025-07-25,6.50,20250725VltPC.pdf,le jog&trail de villers-le-temple_2025-07-25_6.5,A3

In [73]:
df = df[df['Nom'] != "2264 N.N."]

In [74]:
mask = (df['Nom'] == "Mergeai Agnes") & (df["Sexe"] != "F")

df.loc[mask, 'Club'] = "Neuf Moulin"
df.loc[mask, 'Sexe'] = "F"

In [75]:
df[~df["Sexe"].isin(["H", "F", "X"])]

Empty DataFrame
Columns: [Position, Nom, Club, Sexe, Categorie, Position Catégorie, Temps, NomCourse, Date, Distance, source_file, racekey, categorie_harmonisee]
Index: []

# Clubs

In [76]:
df["Club"].unique()

<ArrowStringArray>
[                   'P8',                      '',       'Foulees Du Plai',
           'Run'Essence',                  'Ocan',              'Ser Athl',
           'Seraing Ath',        'Huy / Mj Sport',               'Cap Nrb',
           'Team Marcel',
 ...
 'Les Zouav Es Saivages', 'Les Runne Rs Du Mardi',                   'Ctt',
    'Huy Athle Tic Club',       'L'Equipe Des Ro',       'Martine Tossens',
          'Cindy Ledent',         'Runnersbraing',               'Terbeke',
                 'Zozos']
Length: 3414, dtype: str

Trop de variabilité dans les noms, ils ne seront pas utilisés dans l'analyse.

# Nom des courses

In [77]:
sorted(df["NomCourse"].unique())

['10 Miles De Vyle Tharoul',
 "A Pid Po L'Bwes - Fraiture",
 "A Pid Po L'Bwes - Fraiture En Condroz",
 "A Pid Po L'Bwes - Fraiture I",
 "A Pid Po L'Bwes - Fraiture-En-Condroz",
 "A Pid Po L'Bwes Fraiture",
 'A Travers Nos Forets - Kin',
 'Ap Modave Run - Vierset-Barse',
 'Au Tour De Villers-Aux-Tours',
 'Autour De Villers-Aux-Tours',
 'Aux Alentours Des Huy Miles - Tihange',
 'Bois & Borsu',
 'Bois Et Borsu',
 'Bomal',
 "Corrdida D'Hermalle - Hermalle Sous Huy",
 'Corrida Des Fermes Et Chateaux - Villers-Le-Temple',
 'Corrida Nocturne - Vierset-Barse',
 "Course Nature Du Grand Bois D'Anthisnes",
 'Courses Des Chemins Communaux - Hermalle-Sous-Huy',
 'Entre Vyle & Bois-Et-Borsu',
 'Entre Vyle & Campagne - Vyle',
 'Entre Vyle Et Bois Borsu',
 'Entre Vyle Et Campagne',
 'Entre Vyle Et Campagne - Vyle Et Tharoul',
 'Entre Vyle Et Campagne - Vyle Tharoul',
 'Entre Vyle Et Campagne - Vyle-Tharoul',
 'Entre Vyle Et Campagne A Vyle Et Tharoul',
 'Entre Vyle Ete Campagne - Vyle Et Tharoul',
 'Fraiture',
 'Fraiture En Condroz',
 'Hamoir',
 'Hamoir - Le Blokai',
 'Hermalle Sous Huy',
 'Hermalle-Sous-Huy',
 "Jogging D'Ombret",
 'Jogging De Hamoir',
 'Jogging De La Piscine - Ocquier',
 'Jogging De La Piscine Ocquier',
 'Jogging De La Saint-Nicolas - Marchin',
 'Jogging De Marchin',
 'Jogging De Modave',
 'Jogging De Modave - Modave',
 'Jogging De Nandrin',
 'Jogging De Pailhe',
 'Jogging De Saint Martin - Nandrin',
 'Jogging De Terwagne',
 'Jogging De Vyle-Tharoul',
 'Jogging De Xhoris',
 'Jogging Des 2 Provinces - Bois & Borsu',
 'Jogging Des Chapelles - Xhoris',
 'Jogging Des Deux Provinces - Bois & Borsu',
 'Jogging Des Poudinges - Ombret',
 'Jogging Des Poudingues - Ombret',
 'Jogging Du Blokai - Hamoir',
 'Jogging Du Congo',
 'Jogging Du Congo - Ciney',
 'Jogging Du Foot De Fraiture En Condroz',
 'Jogging Du Giro - Marchin',
 'Jogging Nature - Villers-Aux-Tours',
 'Jogging Saint Martin - Nandrin',
 'Jogging Saint-Martin - Nandrin',
 'Kin',
 "L'Ampsinois",
 'La Barketoise - Vierset-Barse',
 'La Barseketoise - Vierset-Barse',
 'La Clavieroise',
 'La Condrusienne',
 'La Condrusienne - Solieres',
 'La Condrusienne - Solieres | Pmr',
 "La Corrida D'Hermalle",
 "La Corrida D'Hermalle-S-Huy",
 "La Corrida D'Hermalle-Sous-Huy",
 'La Corrida De La Saint Nicolas - Marchin',
 'La Corrida De St Nicolas - Marchin',
 'La Corrida Des Fermes & Chateaux - Villers-Le-Temple',
 'La Corrida Des Fermes Et Chateaux - Villers-Le-Temple',
 "La Ferme D'Achene",
 'La Foulee Anthisnoise - Anthisne',
 'La Foulee Anthisnoise - Anthisnes',
 "La Foulee D'Anthisnes",
 "La Foulee D'Anthisnes - Anthisnes",
 'La Marchoise',
 'La Neupreenne',
 'La Neupreenne - Neupre',
 'La Run Des Gottes - Modave (Stree)',
 "La Run'Essence - Hermalle-Sous-Huy",
 'Le Binameye - Fraiture En Condroz',
 'Le Jgging De La Saint-Nicolas - Marchin',
 'Le Jog&Trail De Villers-Le-Temple',
 'Le Jogging Andre Servotte - Modave',
 'Le Jogging Bmw Delbecq - Seraing',
 "Le Jogging D'Achene",
 'Le Jogging De Barsy',
 'Le Jogging De Hamoir',
 'Le Jogging De Havelange',
 "Le Jogging De L'Ecole - Fraiture-En-Condroz",
 'Le Jogging De La Fete De La Piscine - Ocquier',
 'Le Jogging De La Piscine - Ocquier',
 'Le Jogging De La Saint Nicolas -Marchin',
 'Le Jogging De La Saint-Nicolas - Marchin',
 'Le Jogging De Modave',
 'Le Jogging De Pailhe',
 'Le Jogging De Saint-Nicolas - Marchin',
 'Le Jogging De Seraing',
 'Le Jogging De St Martin - Nandrin',
 'Le Jogging De Terwagne',
 'Le Jogging De Villers Le Temple',
 'Le Jogging De Villers-Le-Temple',
 'Le Jogging Des 2 Provinces',
 'Le Jogging Des 2 Provinces - Bois Er Borsu',
 'Le Jogging Des 2 Provinces - Bois Et Borsu',
 'Le Jogging Des 2 Provinces - Bois-Et-Borsu',
 'Le Jogging Des Coccinelles - Chevetogne',
 'Le Jogging Des Deux Provinces - Bois Et Borsu',
 'Le Jogging Des Poudinges - Ombret',
 'Le Jogging Des Poudinges - Ombret(Cid:10)',
 'Le Jogging Des Poudingues - Ombret',
 'Le Jogging Du Blanc Gravier',
 'Le Jogging Du Blanc Gravier - Liege (Sart-Tilman)',
 'Le Jogging Du Blanc-Gravier - Sart Tilman',
 'Le Jogging Du Chateau - Modave',
 'Le Jogging Du Congo - Ciney',
 'Le Jogging Du Plateau De Frisee',
 'Le Jogging Du Plateau De Frisee - Schaltin',
 "Le Jogging Nocturne De L'Ecole - Fraiture-En-Condroz",
 "Le Jogging Nocturne De L'Ecole De Fraiture",
 "Le Jogging Nocturne De L'Ecole De Fraiture En Condroz",
 'Le Jogging Saint-Martin',
 'Le Jogging Saint-Martin - Nandrin',
 'Le Jogging St-Martin - Nandrin',
 'Le Tour De Les Avins',
 "Les 10 Km Du Grand Bois D'Anthisnes - Villers-Aux-Tours",
 'Les 10 Kms De Pailhe',
 'Les 10 Miles De Vyle-Tharoul',
 'Les 20 Kms De Fraiture En Condroz',
 'Les Avins',
 'Les Dreves De La Vecquee - Seraing',
 'Les Foulees De Saint-Jo',
 'Les Foulees De Tihange',
 'Les Foulees De Tihange - Tihange',
 'Les Foulees Saint-Jo - Gesves',
 'Les Sentiers Du Val - Seraing',
 'Les Sentiers Verts - Marchin',
 'Les Sentiers Verts De Marchin',
 "Les Tidges D'Havlondge",
 "Les Tidges D'Havlondge - Havelange",
 "Les Tidges D'Havlondje - Havelange",
 "Les Tidges D'Havlondje - Havelange(Cid:10)",
 "Les Tidges D'Havlondjes - Havelange",
 'Les Tidges Des Havlondge - Havelange',
 'Li Binameye - Fraiture',
 'Li Binameye - Fraiture En Condroz',
 "Li Binameye Des D'Zys - Fraiture",
 'Lince - Sprimont',
 'Lince Sprimont',
 'Marche',
 'Marchin',
 'Modave',
 'Nandrin',
 'Nandrin Jogging (Saint-Martin)',
 'Neupre',
 'Ocquier',
 'Pailhe',
 'Ronde Des Fermes Et Chateaux - Villers-Le-Temple',
 'Sef : 15 V4F : 0 Seh : 76 V4H : 1',
 'Sef : 29 V4F : 0 Seh : 23 V4H : 0',
 'Seraing',
 'Sprimont',
 'Terwagne',
 'Tihange',
 'Villers Le Temple',
 'Villers-Le-Temple',
 'Vyle Tharoul',
 'Vyle-Tharoul',
 'Weris',
 'Xhoris']

In [78]:
df[df["NomCourse"] == 'Sef : 29 V4F : 0 Seh : 23 V4H : 0' ]

,Position,Nom,Club,Sexe,Categorie,Position Catégorie,Temps,NomCourse,Date,Distance,source_file,racekey,categorie_harmonisee
41151,1,Van Der Zwalmen Sabine,Riwa,F,SEF,1,0:22:06,Sef : 29 V4F : 0 Seh : 23 V4H : 0,2012-06-08,6.0,2012-HCH-CC-VYLE-6.00.pdf,sef : 29 v4f : 0 seh : 23 v4h : 0_2012-06-08_6.0,SD
41152,2,Baudoin Philippe,,H,V1H,1,0:23:15,Sef : 29 V4F : 0 Seh : 23 V4H : 0,2012-06-08,6.0,2012-HCH-CC-VYLE-6.00.pdf,sef : 29 v4f : 0 seh : 23 v4h : 0_2012-06-08_6.0,V1
41153,3,Braquet Martin,,H,ESH,1,0:23:30,Sef : 29 V4F : 0 Seh : 23 V4H : 0,2012-06-08,6.0,2012-HCH-CC-VYLE-6.00.pdf,sef : 29 v4f : 0 seh : 23 v4h : 0_2012-06-08_6.0,ESH
41154,4,Fraineux Jerome,Acvise,H,SEH,1,0:23:42,Sef : 29 V4F : 0 Seh : 23 V4H : 0,2012-06-08,6.0,2012-HCH-CC-VYLE-6.00.pdf,sef : 29 v4f : 0 seh : 23 v4h : 0_2012-06-08_6.0,SH
41155,5,Corswarem Pierre-Henri,Wac,H,SEH,2,0:24:06,Sef : 29 V4F : 0 Seh : 23 V4H : 0,2012-06-08,6.0,2012-HCH-CC-VYLE-6.00.pdf,sef : 29 v4f : 0 seh : 23 v4h : 0_2012-06-08_6.0,SH
...,...,...,...,...,...,...,...,...,...,...,...,...,...
41277,128,Letecheur Marie,,F,ESF,14,0:54:53,Sef : 29 V4F : 0 Seh : 23 V4H : 0,2012-06-08,6.0,2012-HCH-CC-VYLE-6.00.pdf,sef : 29 v4f : 0 seh : 23 v4h : 0_2012-06-08_6.0,ESF
41278,129,Letecheur Clemence,,F,ESF,15,0:54:55,Sef : 29 V4F : 0 Seh : 23 V4H : 0,2012-06-08,6.0,2012-HCH-CC-VYLE-6.00.pdf,sef : 29 v4f : 0 seh : 23 v4h : 0_2012-06-08_6.0,ESF
41279,130,Collette Alexandra,,X,xxx,,0:54:57,Sef : 29 V4F : 0 Seh : 23 V4H : 0,2012-06-08,6.0,2012-HCH-CC-VYLE-6.00.pdf,sef : 29 v4f : 0 seh : 23 v4h : 0_2012-06-08_6.0,XXX
41280,131,Simek Coralie,,F,SEF,29,1:01:06,Sef : 29 V4F : 0 Seh : 23 V4H : 0,2012-06-08,6.0,2012-HCH-CC-VYLE-6.00.pdf,sef : 29 v4f : 0 seh : 23 v4h : 0_2012-06-08_6.0,SD
41281,132,Roy Thomas,,H,SEH,23,1:01:06,Sef : 29 V4F : 0 Seh : 23 V4H : 0,2012-06-08,6.0,2012-HCH-CC-VYLE-6.00.pdf,sef : 29 v4f : 0 seh : 23 v4h : 0_2012-06-08_6.0,SH

In [79]:
mask1 = df['NomCourse'] == "Sef : 15 V4F : 0 Seh : 76 V4H : 1"
mask2 = df['NomCourse'] == "Sef : 29 V4F : 0 Seh : 23 V4H : 0"

df.loc[mask1, 'NomCourse'] = "Les 10 Miles De Vyle-Tharoul"
df.loc[mask2, 'NomCourse'] = "Les 10 Miles De Vyle-Tharoul"

In [80]:
sorted(df['NomCourse'].unique())

['10 Miles De Vyle Tharoul',
 "A Pid Po L'Bwes - Fraiture",
 "A Pid Po L'Bwes - Fraiture En Condroz",
 "A Pid Po L'Bwes - Fraiture I",
 "A Pid Po L'Bwes - Fraiture-En-Condroz",
 "A Pid Po L'Bwes Fraiture",
 'A Travers Nos Forets - Kin',
 'Ap Modave Run - Vierset-Barse',
 'Au Tour De Villers-Aux-Tours',
 'Autour De Villers-Aux-Tours',
 'Aux Alentours Des Huy Miles - Tihange',
 'Bois & Borsu',
 'Bois Et Borsu',
 'Bomal',
 "Corrdida D'Hermalle - Hermalle Sous Huy",
 'Corrida Des Fermes Et Chateaux - Villers-Le-Temple',
 'Corrida Nocturne - Vierset-Barse',
 "Course Nature Du Grand Bois D'Anthisnes",
 'Courses Des Chemins Communaux - Hermalle-Sous-Huy',
 'Entre Vyle & Bois-Et-Borsu',
 'Entre Vyle & Campagne - Vyle',
 'Entre Vyle Et Bois Borsu',
 'Entre Vyle Et Campagne',
 'Entre Vyle Et Campagne - Vyle Et Tharoul',
 'Entre Vyle Et Campagne - Vyle Tharoul',
 'Entre Vyle Et Campagne - Vyle-Tharoul',
 'Entre Vyle Et Campagne A Vyle Et Tharoul',
 'Entre Vyle Ete Campagne - Vyle Et Tharoul',
 'Fraiture',
 'Fraiture En Condroz',
 'Hamoir',
 'Hamoir - Le Blokai',
 'Hermalle Sous Huy',
 'Hermalle-Sous-Huy',
 "Jogging D'Ombret",
 'Jogging De Hamoir',
 'Jogging De La Piscine - Ocquier',
 'Jogging De La Piscine Ocquier',
 'Jogging De La Saint-Nicolas - Marchin',
 'Jogging De Marchin',
 'Jogging De Modave',
 'Jogging De Modave - Modave',
 'Jogging De Nandrin',
 'Jogging De Pailhe',
 'Jogging De Saint Martin - Nandrin',
 'Jogging De Terwagne',
 'Jogging De Vyle-Tharoul',
 'Jogging De Xhoris',
 'Jogging Des 2 Provinces - Bois & Borsu',
 'Jogging Des Chapelles - Xhoris',
 'Jogging Des Deux Provinces - Bois & Borsu',
 'Jogging Des Poudinges - Ombret',
 'Jogging Des Poudingues - Ombret',
 'Jogging Du Blokai - Hamoir',
 'Jogging Du Congo',
 'Jogging Du Congo - Ciney',
 'Jogging Du Foot De Fraiture En Condroz',
 'Jogging Du Giro - Marchin',
 'Jogging Nature - Villers-Aux-Tours',
 'Jogging Saint Martin - Nandrin',
 'Jogging Saint-Martin - Nandrin',
 'Kin',
 "L'Ampsinois",
 'La Barketoise - Vierset-Barse',
 'La Barseketoise - Vierset-Barse',
 'La Clavieroise',
 'La Condrusienne',
 'La Condrusienne - Solieres',
 'La Condrusienne - Solieres | Pmr',
 "La Corrida D'Hermalle",
 "La Corrida D'Hermalle-S-Huy",
 "La Corrida D'Hermalle-Sous-Huy",
 'La Corrida De La Saint Nicolas - Marchin',
 'La Corrida De St Nicolas - Marchin',
 'La Corrida Des Fermes & Chateaux - Villers-Le-Temple',
 'La Corrida Des Fermes Et Chateaux - Villers-Le-Temple',
 "La Ferme D'Achene",
 'La Foulee Anthisnoise - Anthisne',
 'La Foulee Anthisnoise - Anthisnes',
 "La Foulee D'Anthisnes",
 "La Foulee D'Anthisnes - Anthisnes",
 'La Marchoise',
 'La Neupreenne',
 'La Neupreenne - Neupre',
 'La Run Des Gottes - Modave (Stree)',
 "La Run'Essence - Hermalle-Sous-Huy",
 'Le Binameye - Fraiture En Condroz',
 'Le Jgging De La Saint-Nicolas - Marchin',
 'Le Jog&Trail De Villers-Le-Temple',
 'Le Jogging Andre Servotte - Modave',
 'Le Jogging Bmw Delbecq - Seraing',
 "Le Jogging D'Achene",
 'Le Jogging De Barsy',
 'Le Jogging De Hamoir',
 'Le Jogging De Havelange',
 "Le Jogging De L'Ecole - Fraiture-En-Condroz",
 'Le Jogging De La Fete De La Piscine - Ocquier',
 'Le Jogging De La Piscine - Ocquier',
 'Le Jogging De La Saint Nicolas -Marchin',
 'Le Jogging De La Saint-Nicolas - Marchin',
 'Le Jogging De Modave',
 'Le Jogging De Pailhe',
 'Le Jogging De Saint-Nicolas - Marchin',
 'Le Jogging De Seraing',
 'Le Jogging De St Martin - Nandrin',
 'Le Jogging De Terwagne',
 'Le Jogging De Villers Le Temple',
 'Le Jogging De Villers-Le-Temple',
 'Le Jogging Des 2 Provinces',
 'Le Jogging Des 2 Provinces - Bois Er Borsu',
 'Le Jogging Des 2 Provinces - Bois Et Borsu',
 'Le Jogging Des 2 Provinces - Bois-Et-Borsu',
 'Le Jogging Des Coccinelles - Chevetogne',
 'Le Jogging Des Deux Provinces - Bois Et Borsu',
 'Le Jogging Des Poudinges - Ombret',
 'Le Jogging Des Poudinges - Ombret(Cid:10)',
 'Le Jogging Des Poudingues - Ombret',
 'Le Jogging Du Blanc Gravier',
 'Le Jogging Du Blanc Gravier - Liege (Sart-Tilman)',
 'Le Jogging Du Blanc-Gravier - Sart Tilman',
 'Le Jogging Du Chateau - Modave',
 'Le Jogging Du Congo - Ciney',
 'Le Jogging Du Plateau De Frisee',
 'Le Jogging Du Plateau De Frisee - Schaltin',
 "Le Jogging Nocturne De L'Ecole - Fraiture-En-Condroz",
 "Le Jogging Nocturne De L'Ecole De Fraiture",
 "Le Jogging Nocturne De L'Ecole De Fraiture En Condroz",
 'Le Jogging Saint-Martin',
 'Le Jogging Saint-Martin - Nandrin',
 'Le Jogging St-Martin - Nandrin',
 'Le Tour De Les Avins',
 "Les 10 Km Du Grand Bois D'Anthisnes - Villers-Aux-Tours",
 'Les 10 Kms De Pailhe',
 'Les 10 Miles De Vyle-Tharoul',
 'Les 20 Kms De Fraiture En Condroz',
 'Les Avins',
 'Les Dreves De La Vecquee - Seraing',
 'Les Foulees De Saint-Jo',
 'Les Foulees De Tihange',
 'Les Foulees De Tihange - Tihange',
 'Les Foulees Saint-Jo - Gesves',
 'Les Sentiers Du Val - Seraing',
 'Les Sentiers Verts - Marchin',
 'Les Sentiers Verts De Marchin',
 "Les Tidges D'Havlondge",
 "Les Tidges D'Havlondge - Havelange",
 "Les Tidges D'Havlondje - Havelange",
 "Les Tidges D'Havlondje - Havelange(Cid:10)",
 "Les Tidges D'Havlondjes - Havelange",
 'Les Tidges Des Havlondge - Havelange',
 'Li Binameye - Fraiture',
 'Li Binameye - Fraiture En Condroz',
 "Li Binameye Des D'Zys - Fraiture",
 'Lince - Sprimont',
 'Lince Sprimont',
 'Marche',
 'Marchin',
 'Modave',
 'Nandrin',
 'Nandrin Jogging (Saint-Martin)',
 'Neupre',
 'Ocquier',
 'Pailhe',
 'Ronde Des Fermes Et Chateaux - Villers-Le-Temple',
 'Seraing',
 'Sprimont',
 'Terwagne',
 'Tihange',
 'Villers Le Temple',
 'Villers-Le-Temple',
 'Vyle Tharoul',
 'Vyle-Tharoul',
 'Weris',
 'Xhoris']

# Distance des courses

In [81]:
race1_mask = df["source_file"] == "2012-CONDRUSIEN-MODAVE-11.30.pdf"
race2_mask = df["source_file"] == "210807-CONDRUSIEN-GOAL TIMING-VILLERS AUX TOURS-5000.pdf"
race3_mask = df["source_file"] == "2015-CONDRUSIEN-FRAITURE 2- 5.29.pdf"
race4_mask = df["source_file"] == "2015-CONDRUSIEN-FRAITURE 2- 9.2.pdf"

df.loc[race1_mask, 'Distance'] = 11.3
df.loc[race2_mask, 'Distance'] = 5.5
df.loc[race3_mask, 'Distance'] = 5.29
df.loc[race4_mask, 'Distance'] = 9.2

# Coureurs

In [82]:
# suppression entrées avec nom qui commence par un chiffre
mask_nom = df['Nom'].str.match(r'^\d', na=False)
df.drop(df[mask_nom].index, inplace=True)

#suppression des #N/A
df.drop(df[df["Nom"]=="#N/A"].index, inplace=True)

# Correction de Simonet Yves
df.loc[df['Nom'] == "(Cid:10)Simonet Yves", 'Nom'] = "Simonet Yves"

In [83]:
sorted(df["Nom"].unique())

['A A',
 'Aaa Bbb',
 'Aarnoutse Pieter',
 'Abascal Bruno',
 'Abbruzzese Sabrina',
 'Abbruzzezse Sabrina',
 'Abdalah Moussa',
 'Abdelkafi Hedi',
 'Abdelman Vincent',
 'Abdelmoumne Mohamed',
 'Abdelmoumni',
 'Abdelmoumni Mohamed',
 'Abdelmounani Mohamed',
 'Abduli Ilir',
 'Abdullahi Mohamed',
 'Abdullani Mohamed',
 'Abdulramman Moubarak',
 'Aberle Manfred',
 'Abid Hedia',
 'Abinet Estelle',
 'Abo Jrai Mohammed',
 'Aboubakr Omar',
 'Aboumerrouane Rihab',
 'Abraham Christophe',
 'Abraham Jean-Francois',
 'Abraham Vinciane',
 'Abraham Zellian',
 'Abrans Maxime',
 'Abrassart Jacqueline',
 'Absil Bertrand',
 'Absil Joel',
 'Absil Patrick',
 'Accary Florence',
 'Achaert Yves',
 'Ackaert Noel',
 'Ackaert Yves',
 'Ackrert Yves',
 'Acquistapace Sarah',
 'Acusilas Jean-Yves',
 'Adam Adrien',
 'Adam Camille',
 'Adam Catherine',
 'Adam Christelle',
 'Adam Christian',
 'Adam Colin',
 'Adam Damien',
 'Adam Emilien',
 'Adam Gilles',
 'Adam Gregory',
 'Adam Jean Christophe',
 'Adam Jean Philippe',
 'Adam Jean-Christophe',
 'Adam Katherine',
 'Adam Manon',
 'Adam Melanie',
 'Adam Olivier',
 'Adam Pascal',
 'Adam Remy',
 'Adam Sebastien',
 'Adam Stephane',
 'Adam Valerie-Anne',
 'Adani Romain',
 'Adans-Dester Bernard',
 'Adant Romain',
 'Adant Stephanie',
 'Adar Stephane',
 'Adrien Philippart De Foy',
 'Adriouchi Abdelilah',
 'Aendkerk Nicolas',
 'Aernoudts Steve',
 'Aerts Bancken Alexandre',
 'Aerts Cathlyne',
 'Aerts Jean',
 'Aerts Sophie',
 'Aerts-Bancken Alexandre',
 'Afano Marielene',
 'Agema Edwin',
 'Agie Gilles',
 'Agier Ludovic',
 'Agneessens Fanny',
 'Agnello Arnaud',
 'Agnello Blaise',
 'Agnello Jean-Pierre',
 'Agnello Manon',
 'Agnello Quentin',
 'Agnello Rosario',
 'Agnessen Anne',
 'Agnoli Anthony',
 'Agolli Florida',
 'Aguer Ludovic',
 'Aguzzi Rene',
 'Ahdre Pelo',
 'Ahnadzi Sohbatkhan',
 'Aidans Jonathan',
 'Aidans Laurent',
 'Airplane Jefferson',
 'Airuhoyuwa Peter',
 'Ait Saadi Idir',
 'Ait-Saadi Idir',
 'Aitsaadi Idir',
 'Akhundzada Noorullhoda',
 'Akkermans Christian',
 'Aksahin Melissa',
 'Al Hashimi Aws',
 'Al-Saadi Zakarjya',
 'Alaimo Valerie',
 'Alain Megane',
 'Alardot Jonathan',
 'Alardot Jonathan Francine',
 'Alavarez Frederic',
 'Alba Carlo',
 'Albanese Dominique',
 'Albanese Maxime',
 'Albart Laurence',
 'Albech Brigitte',
 'Albert Amile',
 'Albert Emile',
 'Albert Emilie',
 'Albert Geoffroy',
 'Albert Gregoire',
 'Albert Gregory',
 'Albert Johann',
 'Albert Louis',
 'Albert Michel',
 'Albert Olivier',
 'Albert Valerie',
 'Albert Vero',
 'Albert Veronique',
 'Albert Vincent',
 'Albertani Patrice',
 'Albessar Philippe',
 'Albessard Francois',
 'Albessard Marine',
 'Albessard Philippe',
 'Albessard Yves',
 'Albessart Francois',
 'Albores Roberto',
 'Alborez Roberto',
 'Alcover Michael',
 'Aldenhoff Arthur',
 'Alderson Regime',
 'Alderson Regine',
 'Alen John',
 'Alendra Cyrille',
 'Alessi Sabrina',
 'Alexandre Alexandre',
 'Alexandre Alysson',
 'Alexandre Amandine',
 'Alexandre Christophe',
 'Alexandre Cyrilel',
 'Alexandre Cyrille',
 'Alexandre Francoise',
 'Alexandre Marie',
 'Alexandre Marie Amelie',
 'Alexandre Marie-Astrid',
 'Alexandre Maxime',
 'Alexandre Pascal',
 'Alexandre Philippe',
 'Alexandrescau Ada',
 'Alexandroff Carole',
 'Alexendre Pascal',
 'Alexis Mailys',
 'Alexis Pascal',
 'Alfano Giuseppe',
 'Alfano Lina',
 'Alfier Laetitia',
 'Ali Haidar Hussaini',
 'Aliberto Stephane',
 'Alie Denis',
 'Alin Leonnis',
 'Alison Danloy',
 'Alken Laurent',
 'Allard Charles',
 'Allard Derec',
 'Allard Derek',
 'Allard Marie-Pascale',
 'Allard Veronique',
 'Allard Vincent',
 'Allepuz Fuster Paula',
 'Alles Ingrid',
 'Almeida Carlos',
 'Almeida Corlos',
 'Almin Thibaut',
 'Aloise Giltay',
 'Alsteen Michel',
 'Alsteens Yannick',
 'Altenhoven Oceane',
 'Altomare Xavier',
 'Alvado Alexandre',
 'Alvarez Barrera Raul',
 'Alvarez Espinila Olga',
 'Alvarez Zapico Clara',
 'Alves Jorge',
 'Amadini Emmanuel',
 'Amana Francois',
 'Amand Francois',
 'Amand Ludivic',
 'Amand Ludovic',
 'Amar Majid',
 'Amaud Ludovic',
 'Amaudrut Jonathan',
 'Amborski Pawel',
 'Ambroise Edouard',
 'Ambrosio Lorenzo',
 'Amelinck Elise',
 'Amen Nicole',
 'Ameri Hugo',
 'Ameur Mohammed',
 'Amichia Fred',
 'Aminta Nicolas',
 'Amiral Kevin',
 'Amirouche Martin',
 'Ammed Mustafa',
 'Amor Y Suarez Cesar',
 'Amor Y Suarez Cesario',
 'Amor Y Suarez Kevin',
 'Amormino Eric',
 'Amormino Erico',
 'Amory Christine',
 'Amory Hugues',
 'An Dre Isabelle',
 'Anceau Jerome',
 'Anciaux Augustin',
 'Anciaux Cassian',
 'Anciaux Clarisse',
 'Anciaux Julien',
 'Anciaux Laura',
 'Anciaux Stephane',
 'Anciaux Victor',
 'Ancion Alain',
 'Ancion Amy',
 'Ancion Arnaud',
 'Ancion Arnaud Raymond',
 'Ancion Arry',
 'Ancion Barielsa',
 'Ancion Carole',
 'Ancion Cecile',
 'Ancion Cedrid',
 'Ancion Charlotte',
 'Ancion Christophe',
 'Ancion Clementine',
 'Ancion Emma',
 'Ancion Enzo',
 'Ancion Etienne',
 'Ancion Gilles',
 'Ancion Jean-Pascal',
 'Ancion Jran Pascal',
 'Ancion Laura',
 'Ancion Marieelsa',
 'Ancion Olivier',
 'Ancion Simon',
 'Andernack Eline',
 'Andernack Melanie',
 'Andre Alain',
 'Andre Ambroise',
 'Andre Carlos',
 'Andre Caroline',
 'Andre Cecile',
 'Andre Claud',
 'Andre Claude',
 'Andre Claudette',
 'Andre David',
 'Andre Ehx',
 'Andre Estelle',
 'Andre Fregory',
 'Andre Geoffrey',
 'Andre Gregory',
 'Andre Guillaume',
 'Andre Iasbelle',
 'Andre Isabelle',
 'Andre Isaline',
 'Andre Jean-Eric',
 'Andre Lilie',
 'Andre Maryse',
 'Andre Pascal',
 'Andre Pelo',
 'Andre Pierre',
 'Andre Rudy',
 'Andre Sebastien',
 'Andren Maud',
 'Andreon Adrien',
 'Andreou Adrien',
 'Andres Michael',
 'Andrianne Colin',
 'Andrianne Guillaume',
 'Andrianne Isabelle Claudine',
 'Andrien Eric',
 'Andrien Maud',
 'Andries Daniel',
 'Andries Yves',
 'Andry Catherine',
 'Anelli Jonathan',
 'Aneve Christophe',
 'Angeli Mathilde',
 'Angelicchio Frederic',
 'Angelini Gladys',
 'Angenot Arnaud',
 'Angenot Etienne',
 'Anglade Amandine',
 'Anglebert Paulilne',
 'Anicion Barielsa',
 'Animali Mario',
 'Ankri Jeremie',
 'Anlia Kevin',
 'Anlion Christophe',
 'Anlion Gilles',
 'Anne Reynders',
 'Annet Gaetan',
 'Annet Philippe',
 'Anquet Virginie',
 'Ansay Geraldine',
 'Ansiaux Annick',
 'Ansiaux Christophe',
 'Ansseau Camille',
 'Antennis Anne-Elise',
 'Anteunis Anne Lise',
 'Anteunis Anne-Lise',
 'Antheunis Valentine',
 'Anthierens Geoffrey',
 'Anthierens Pierre',
 'Anthone Thomas',
 'Antinucci Sandra',
 'Antoine',
 'Antoine Alain',
 'Antoine Alexandre',
 'Antoine Baptiste',
 'Antoine Bockiau',
 'Antoine Boris',
 'Antoine Caroline',
 'Antoine Christophe',
 'Antoine Jean-Batiste',
 'Antoine Julie',
 'Antoine Laurence',
 'Antoine Michael',
 'Antoine Nicolas',
 'Antoine Pascal',
 'Antoine Valerie',
 'Antomme Yves',
 'Antonelli Cindy',
 'Antonini Romain',
 'Antoniotti Eva',
 'Anzalone Damien Andre',
 'Anzalone Salvatore',
 'Anzalone Victoria',
 'Aouicha Antoine',
 'Aoust Rudy',
 'Apa Zoltan',
 'Aparerido Fernandes Barges',
 'Appeldoorn Charlotte',
 'Appeldoorn Chloe',
 'Appeldoorn Fanny',
 'Appeldoorn Maike',
 'Appeldoorn Patricia',
 'Appeltams Helene',
 'Appeltans Helene',
 'Appeltants Helene',
 'Appermans Alain',
 'Applincourt Florence',
 'Applincourt Jean Pierre',
 'Applincourt Jean-Pierre',
 'Applincourt Julien',
 'Arambatzis Fabian',
 'Arauxo Lou',
 'Archal Dimitri',
 'Archambeau Christine',
 'Archambeau Frederic',
 'Archambeau Julie',
 'Archambeau Nicolas',
 'Archambeau Roger',
 'Archambeau Sacha',
 'Archambeau Tommi',
 'Archamleau Sacha',
 'Archembeau Roger',
 'Archer Yves',
 'Archidona Martinez Laura',
 'Arenas Mara',
 'Arenas Sanchez Maria Mara',
 'Arend Dominique',
 'Arend Dylan',
 'Arend Julie',
 'Arend Virginie',
 'Arens Jill',
 'Arens Jonathan',
 'Argento Anael',
 'Argento Carmela',
 'Argento Carmelo',
 'Argento Francesco',
 'Argento Francois',
 'Argento Lisandro',
 'Argento Maite',
 'Arguelles Sarah',
 'Arickx Emmanuel',
 'Arifi Besfort',
 'Arincon Torres Nicolas',
 'Arincon Torres Sebastien',
 'Aristi Roberto',
 'Arnaud Dony',
 'Arnold Jeremy',
 'Arnold Pascal',
 'Arnold Pierre',
 'Arnoldy Astrid',
 'Arnolis Catherine',
 'Arnols Vadim',
 'Arnoud Jerome',
 'Arnould Aurore',
 'Arnould Cindy',
 'Arnould Delphine',
 'Arnould Jerome',
 'Arnould Kevin',
 'Arnould Leo',
 'Arnould Nathalie',
 'Arnould Sylvie',
 'Arnould Veronique',
 'Arny Dimitri',
 'Arquin Maxime',
 'Arrive Pas Premier Gene',
 'Arsene Stassart',
 'Art Frederic',
 'Arthus Evelyne',
 'Arts Emilien',
 'Arts Romane',
 'Artus Eve',
 'Artus Eveline',
 'Artus Evelyne',
 'Artus Evelyne Josee',
 'Artus Frederic',
 'Artus Marvin',
 'Artus Nathalie',
 'Arys Dominique',
 'Aschman Axel',
 'Aslan Yaser',
 'Aslanov Samuel',
 'Aspiotis Magali',
 'Assabri Ali',
 'Assemacker Tiphany',
 'Assenmacker Tiphany',
 'Assenmaker Fabian',
 'Assenmaker Lohan',
 'Assenmarer Robin',
 'Assez Sebastian',
 'Astolfi Damien',
 'Astolfi Remy',
 'Atangana Paul',
 'Atol Peter',
 'Atta Jonathan',
 'Atta Nathan',
 'Attolini Adriano',
 'Attout Bruno',
 'Attout Joseph',
 'Aubert Emile',
 'Auboiron Jeanne',
 'Aubry Anais',
 'Aubry Gautier',
 'Aubry Julie',
 'Aubry Mathieu',
 'Audenaert Jeoffrey',
 'Audenaert Joffrey',
 'Audrit Philippe',
 'Audrit Sarah',
 'Auet Vincent',
 'Augusto Marcos Maxie',
 'Auquier Gery',
 'Aurore Aurore',
 'Auwers Sylvie',
 'Avart Kevin',
 'Averno Fabrice',
 'Avril Claire',
 'Avril Marion',
 'Ayao Koami Yossud',
 'Aysolmaz Banu',
 'Aze Julien',
 'Azevedo Jose',
 'Azuzi Maliha',
 'Azuzi Marjan',
 'Azzguz Kamal',
 'Azzolini Adriano',
 'Azzolini Philippe',
 'Azzous Kamaz',
 'Azzouz Kamal',
 'Azzouz Kamaz',
 'Azzouz Samira',
 'B B',
 'Baar Alexandra',
 'Babe Michel',
 'Babylas Jocelyne',
 'Babza Thibaud',
 'Baccaert Nicolas',
 'Baccaro Vincenzo',
 'Baccichet Aurelie',
 'Baccichet Fulvio',
 'Baccus Morgane',
 'Bachelet Justin',
 'Back Delphine',
 'Backelandt Geoffrey',
 'Backx Christian',
 'Backy Florian',
 'Baclene Valerie',
 'Baclene Xavier',
 'Baclin Angelique',
 'Bacquelaine Nancy',
 'Bada Ariane',
 'Bada Arnaud',
 'Bada Christine',
 'Bada Florian',
 'Bada Herve',
 'Bada Marie',
 'Bada Monique',
 'Badenberg Bernard',
 'Bader Regis',
 'Badon Marie Helene',
 'Badon Marie-Helene',
 'Badot Felicien',
 'Badot Francois',
 'Badoux Florian',
 'Baeckelandt',
 'Baeckelandt Christophe',
 'Baeckelandt Debora',
 'Baeckelandt Drazik',
 'Baeckelandt Geoffrey',
 'Baeckelandt Lara',
 'Baeckelandt Marcel',
 'Baeke Clara',
 'Baeke Jerome',
 'Bael Katrien',
 'Baele Ariel',
 'Baele Paul',
 'Baele Pavel',
 'Baens Jennifer',
 'Baert David',
 'Baert Eric',
 'Baert Odile',
 'Baeten Annick',
 'Baeten Damien',
 'Baeten Edith',
 'Baeten Yvan',
 'Baetens Damien',
 'Baeulieu Aurore',
 'Baeyen Andre',
 'Baeyen Juliette',
 'Baeyens Gilles',
 'Baggetto Luc',
 'Baggio Livio',
 'Baggio Raphael',
 'Baglioni Tayan',
 'Baguette Appoline',
 'Baguette Celine',
 'Baguette Elodie',
 'Bah Traore Abdel',
 'Bahi Rachid',
 'Baijot Eric',
 'Baijot Guillaume',
 'Baijot Julien',
 'Baijot Nicolas',
 'Baikrich Amelien',
 'Baikrich Koralie',
 'Baikrich Michael',
 'Baillet Loic',
 'Baillet Tom',
 'Bailleux Celine',
 'Baillez Johnny',
 'Bailly Amaury',
 'Bailly Carine',
 'Bailly Caroline',
 'Bailly Christophe',
 'Bailly Coraline',
 'Bailly Jacques',
 'Bailly Laurent',
 'Bailly Lea',
 'Bailly Luc',
 'Bailly Quentin',
 'Baily Damien',
 'Baily Valerie',
 'Bair Stephane',
 'Bairin Charline',
 'Baiverlin Luc',
 'Baiwir Esrher',
 'Baiwir Esther',
 'Baiwir Laura',
 'Baiwir Yves',
 'Bajramovic Amel',
 'Bakowski Mathieu',
 'Balaes Delphine',
 'Balaguera Gabriel',
 'Balancier Jacques',
 'Balant Adrien',
 'Balaux Jacqueline',
 'Balbeur Benjamin',
 'Balcaen Yannick',
 'Balczunas Magali',
 'Baldewyns Catherine',
 'Baldin Jerome',
 'Baldini Jerome',
 'Baldo Fabian',
 'Balhan Catherine',
 'Balhan Paul',
 'Balhant Stephanie',
 'Balieu Olivier',
 'Ballant Adrien',
 'Balleunas Magali',
 'Balleux Christophe',
 'Balleux Marine',
 'Balleux Severine',
 'Ballmann Dany',
 'Balmant Stephanie',
 'Balon Dom',
 'Balon Dominique',
 'Balon Motoel Dom',
 'Balon Sandrine',
 'Balsam Luc',
 'Balsan Luc',
 'Baltazard Charlotte',
 'Balten Barry',
 'Balter Elea',
 'Balthasar Francis',
 'Balthasart Justine',
 'Balthasart Maurine',
 'Balthasart Olivier',
 'Balthazar Marie',
 'Balthazart Alain',
 'Balthazart Camille',
 'Balthazart Nicolas',
 'Baltus',
 'Baltus Anne',
 'Baltus Christiane',
 'Baltus Christiane Marie-Louise',
 'Baltus Eric',
 'Baltus Francoise',
 'Baltus Julie',
 'Baltus Julien',
 'Baltus Loghan',
 'Baltus Perrine',
 'Baltus Renaud',
 'Baltus Ronan',
 'Baltus Sophie',
 'Balzat Sona',
 'Balzat Sonia',
 'Bammens Andre',
 'Bancu Olivier',
 'Bandino Thomas',
 'Bandon Maud',
 'Banf Martin',
 'Bangels Xavier',
 'Bank Martin',
 'Bannabe Michel',
 'Banneux Cedric',
 'Banneux Cyrille',
 'Banterla Julien',
 'Banterla Romeo',
 'Banx Martin',
 'Baonville Isabelle',
 'Baonville Julie',
 'Baptiste Balis Baptiste',
 'Baptiste Celine',
 'Baquet Thomas',
 'Bar Stephanie',
 'Baradel Oceane',
 'Baraka Nou',
 'Barankiewicz Simon',
 'Baranov Alexandr',
 'Baranov Alexandre',
 'Barattin Muriel',
 'Baratto Tiffany',
 'Barbagallo Nathalie',
 'Barban Ornella',
 'Barbe Delphine',
 'Barbe Yhomas',
 'Barbeaux Julie',
 'Barbee Delphine',
 'Barbee Loic',
 'Barbencon Jeremy',
 'Barbie Bettremieux',
 'Barbier Amandine',
 'Barbier Catherine',
 'Barbier Christophe',
 'Barbier Jacqueline',
 'Barbier Jean',
 'Barbier Jerome',
 'Barbier Martin',
 'Barbier Stamy',
 'Barbier Veronique',
 'Barbieux Patrice',
 'Barbion Melodie',
 'Barcaro Hugo',
 'Barcaro Hugu',
 'Barcia Maria',
 'Barcy Cedric',
 'Bardin Louane',
 'Bare Alice',
 'Bare Julie',
 'Bare Nicolas',
 'Bare Sebastien',
 'Barette Emmanuel',
 'Barette Manu',
 'Barette Victor',
 'Barile Nicola',
 'Barkhuis Kirstin',
 'Barla Sophie',
 'Barmasai Serge',
 'Barnabe Karin',
 'Barni Julien',
 'Barnich Julie',
 'Barnich Valerie',
 'Baron Emmanuel',
 'Baron Jean',
 'Baron Jean-Marie',
 'Baron Magali',
 'Baron Nicolas',
 'Baroni Roland',
 'Barranco Sebastien',
 'Barroit Dominique',
 'Barsi Julie',
 'Barsi Loic',
 'Bartelet Danielle',
 'Bartelet Joel',
 'Barthelemy Anouck',
 'Barthelemy Laurie',
 'Barthelemy Magali',
 'Barthelemy Stephane',
 'Bartholome Andrea',
 'Bartholome Benjamin',
 'Bartholome Bernard',
 'Bartholome David',
 'Bartholome Didier',
 'Bartholome Gregory',
 'Bartholome Marie-Christine',
 'Bartholome Valentin',
 'Bartiaux Jean-Marc',
 'Bartin Christophe',
 'Bartocci Danilo',
 'Bartocci Dnillo',
 'Bartolomeu Cerqueira',
 'Bartolozzi Augusto',
 'Barton Nathalie',
 'Bartrand Jean-Louis',
 'Barzin Adien',
 'Barzon Adrien',
 'Basciu Vilma',
 'Basien Thierry',
 'Basilio Valery',
 'Bassens Maud',
 'Basso Hicham',
 'Basso Martin',
 'Bassou Hicham',
 'Bassoulet Jean-Claude',
 'Bastagne Jacques',
 'Bastagne Laurence',
 'Bastagne Melanie',
 'Bastagne Nico',
 'Bastens Arnaud',
 'Bastiaensen Rene',
 'Bastian Ronald',
 'Bastianelli Elora',
 'Bastianelli Fabian',
 'Bastianelli Fagian',
 'Bastianelli Laurent',
 'Bastianelli Vincent',
 'Bastiannelli Laurent',
 'Bastide Corine',
 'Bastien Benoit',
 'Bastin Cathy',
 'Bastin Cedric',
 'Bastin Cedric Jonathan',
 'Bastin David',
 'Bastin Dominique',
 'Bastin Emile',
 'Bastin Emilien',
 'Bastin Fanny',
 'Bastin Florence',
 'Bastin Guy',
 'Bastin Jean-Luc',
 'Bastin Julien',
 'Bastin Laetitia',
 'Bastin Mailys',
 'Bastin Marie-Pierre',
 'Bastin Mathieu',
 'Bastin Milan',
 'Bastin Quentin',
 'Bastin Raphael',
 'Bastin Renaud',
 'Bastin Ruben',
 'Bastin Thibault',
 'Bastin Thierry',
 'Bastin Veronique',
 'Bastin Xavier',
 'Bastin Yasmine',
 'Bastin Yoann',
 'Bastogne Louis',
 'Bastogne Melanie',
 'Bastogne Olivier',
 'Bataille Damien',
 'Bataille Elise',
 'Bataille Remy',
 'Bataille Thierry',
 'Batinic Xavier',
 'Battaglia Amandine',
 'Battaglia Anthony',
 'Battaglini Stephane',
 'Batter Emilien',
 'Batter Laure',
 'Battisti Gilles',
 'Battistini Luciano',
 'Battistini Luliano',
 'Baucama David',
 'Baucamp Charlotte',
 'Baucamp David',
 'Baucamp Elise',
 'Baucamp Eloise',
 'Baucamp Kevin',
 'Baucamp Maureen',
 'Baucamp Muriel',
 'Baucamp Sylvain',
 'Bauche Stephan',
 'Baudelet Matteo',
 'Baudenne Camille',
 'Baudhuin Yves',
 'Baudier Rene',
 'Baudinet Caroline',
 'Baudinet Jean Pierre',
 'Baudinet Jean-Pierer',
 'Baudinet Jean-Pierre',
 'Baudinet Pierre',
 'Baudoin Anne Francoise',
 'Baudoin Anne-Francoise',
 'Baudoin Annefrancoise',
 'Baudoin Arthur',
 'Baudoin Cesar',
 'Baudoin Chantal',
 'Baudoin Clement',
 'Baudoin Constance',
 'Baudoin Francois',
 'Baudoin Gauthier',
 'Baudoin Geraldine',
 'Baudoin Juliette',
 'Baudoin Marie',
 'Baudoin Meganne',
 'Baudoin Michel',
 'Baudoin Pauline',
 'Baudoin Philippe',
 'Baudoin Phili¨¨E',
 'Baudoin Vinciane',
 'Baudoin Vincianne',
 'Baudot Chistophe',
 'Baudot Christophe',
 'Baudot Marielle',
 'Baudot Thomas',
 'Baudouin Anne-Francoise',
 'Baudouin Leona',
 'Baudouin Michel',
 'Baudouin Philippe',
 'Baudoux Beneoit',
 'Baudry Augusta',
 'Baudry Elsa',
 'Baudry Hugo',
 'Baudson Benedicte',
 'Bauduin Cecile',
 'Bauduine Xavier',
 'Bauffe Nathalie',
 'Baugnee Simon',
 'Baugnet Damien',
 'Baugnet Joelle',
 'Baugnet Murielle',
 'Baugnet Vinciann',
 'Baugnet Vincianne',
 'Baugniet Christophe',
 'Baugniet Jade',
 'Baugniet Philippe',
 'Baujdaut Xx',
 'Bauly Mathieu',
 'Baum Cyrille',
 'Baumans Benoit',
 'Baumans Benoit Albert',
 'Baumans Hugues',
 'Baumans Jean Luc',
 'Baumans Jean-Luc',
 'Baumans Johan',
 'Baumans Patrick',
 'Baumans Pierre-Emmanuel',
 'Baumans Virginie',
 'Baumont Patrick',
 'Bauraing David',
 'Baurin Dorian',
 'Baurin Frederic',
 'Baurin Fredreric',
 'Baurin Lea',
 'Baus Caroline',
 'Baus Clara',
 'Baus Jose',
 'Baus Nathalie',
 'Bauvir Baptiste',
 'Bauwens Benoit',
 'Bauwens Caroline',
 'Bauwens Christophe',
 'Bauwens Clarisse',
 'Bauwens Florence',
 'Bauwens Frederic',
 'Bauwens Sarah',
 'Bauwin Bertrand',
 'Bavonet Vincianne',
 'Bawin Benjamin',
 'Bawin Benoit',
 'Bawin Frederic',
 'Bawin Julie',
 'Bawin Krystel',
 'Bawin Maxence',
 'Bawin Raphael',
 'Bawin Regis',
 'Bay Christelle',
 'Bay Elodie',
 'Bay Maud',
 'Bayard Julien',
 'Bayard Pierre',
 'Bayard Sophie',
 'Bayens Hilde',
 'Bayers Frederic',
 'Bayers Stephanie',
 'Bayet Adrien',
 'Bayet Arnaud',
 'Bayet Caroline',
 'Bayet Cedric',
 'Bayet Corine',
 'Bayet Etienne',
 'Bayet Lorine',
 'Baylli Amaury',
 'Bayonne Frederic',
 'Bayonnet Frederic',
 'Bayonnet Julien',
 'Bayron Talitha',
 'Bayrou Abel',
 'Bayrou Talitha',
 'Bazdoulj Nathalie',
 'Bazelaire Charlotte',
 'Bazerque Marceline',
 'Bazi Michel',
 'Bazzani Vanessa',
 'Bea',
 'Bea F',
 'Bea Titude',
 'Bearam Zomaomi',
 'Bearelle Sophie',
 'Bearts David',
 'Bearzatto Claudia',
 'Beauboire Brieux',
 'Beaucamp Maureen',
 'Beauclercq Jean-Yves',
 'Beauclercq Margaux',
 'Beaudion Xavier',
 'Beaudoin Benjo',
 'Beaudoin Xavier',
 'Beaudot Julie',
 'Beaudot Marc',
 'Beaudouin Benjamin',
 'Beaudouin Xavier',
 'Beaudry Adeline',
 'Beauduin Alexis',
 'Beauduin Benjamin',
 'Beauduin Marie-Noel',
 'Beauduin Marienoel',
 'Beauduin Xavier',
 'Beauduine Xaviere',
 'Beaufays Chloe',
 'Beaufays Yvan',
 'Beaufont Anne',
 'Beaufort Alex',
 'Beaufort Fallais Anne',
 'Beaufort Laurence',
 'Beaufort Pierre',
 'Beaufort Vincent',
 'Beaufort-Fallais Anne',
 'Beaujean Alain',
 'Beaujean Caroline',
 'Beaujean Catherine',
 'Beaujean Gregory',
 'Beaujean Gregory Jean-Pol',
 'Beaujean Marie',
 'Beaujean Olivier',
 'Beaujean Olivier Olivier',
 'Beaujean Remy',
 'Beaujean Valerie',
 'Beaujieu Laure',
 'Beaujot Antoine',
 'Beaulieu Anne-Lise',
 'Beaulieu Aurore',
 'Beaulieu Justine',
 'Beaulieu Laure',
 'Beaulieu Melisande',
 'Beaulieu Melissande',
 'Beaumet Julien',
 'Beaumez Quentin',
 'Beaumont Bertrand',
 'Beaumont Caroline',
 'Beaumont Denis',
 'Beaumont Gregory',
 'Beaumont Julien',
 'Beaumont Laura',
 'Beaumont Laurent',
 'Beaumont Quentin',
 'Beaumont Sonia',
 'Beaupain Cedric',
 'Beaupain David',
 'Beauprez Clement',
 ...]

In [84]:
names = ['Abdelmoumne Mohamed',
 'Abdelmoumni',
 'Abdelmoumni Mohamed',
 'Abdelmounani Mohamed',
 'Abdullahi Mohamed',
 'Abdullani Mohamed']

df[df['Nom'].isin(names)]

,Position,Nom,Club,Sexe,Categorie,Position Catégorie,Temps,NomCourse,Date,Distance,source_file,racekey,categorie_harmonisee
31543,9,Abdullani Mohamed,,H,SEH,7,0:44:55,Villers-Le-Temple,2011-07-29,12.00,2011 - CONDRUZIEN - VILLERS-LE-TEMPLE (11.47).pdf,villers-le-temple_2011-07-29_12.0,SH
35486,3,Abdullahi Mohamed,,H,SE,3,0:34:53,Pailhe,2010-09-17,10.00,2010 - ARCHIVE - PAILHE (10.0).pdf,pailhe_2010-09-17_10.0,SH
47882,53,Abdelmounani Mohamed,,H,SEN,30,0:49:05,Li Binameye - Fraiture,2014-09-27,9.30,2014-CONDRUSIEN-NEW2-FRAITURE-9.3.pdf,li binameye - fraiture_2014-09-27_9.3,SH
49587,8,Abdullani Mohamed,,H,SEH,7,0:40:43,Terwagne,2012-04-20,10.90,2012-CONDRUSIEN-TERWAGNE-10.90.pdf,terwagne_2012-04-20_10.9,SH
53055,24,Abdelmoumni,Tri-Tra-Raid,H,V1,7,00:41:36,La Corrida D'Hermalle-S-Huy,2025-07-19,10.00,20250719HermalleGC.pdf,la corrida d'hermalle-s-huy_2025-07-19_10.0,V1
55317,3,Abdullahi Mohamed,,H,SEH,2,0:54:28,Bois & Borsu,2012-05-05,14.70,2012-CONDRUSIEN-BOIS&BORSU-14.70.pdf,bois & borsu_2012-05-05_14.7,SH
58889,3,Abdullahi Mohamed,,H,SE,2,1:18:41,Fraiture En Condroz,2010-09-25,19.55,2010 - ARCHIVE - FRAITURE II (19.5).pdf,fraiture en condroz_2010-09-25_19.55,SH
60291,29,Abdullani Mohamed,,H,SEH,16,0:49:37,Les Avins,2012-02-25,12.00,2012-CONDRUSIEN-LES AVINS-12.00.pdf,les avins_2012-02-25_12.0,SH
66013,20,Abdelmoumni Mohamed,Ttrs,H,V1,8,00:44:12,La Corrida D'Hermalle-Sous-Huy,2023-07-20,10.40,230720-CONDRUSIEN-GOALTIMING-LA CORRIDA D_HERM...,la corrida d'hermalle-sous-huy_2023-07-20_10.4,V1
66346,214,Abdelmoumne Mohamed,,H,SEN,87,0:59:28,La Neupreenne - Neupre,2015-03-15,10.84,2015-CONDRUSIEN-NEUPREENNE-NEUPRE-10.84.pdf,la neupreenne - neupre_2015-03-15_10.84,SH
75864,85,Abdelmoumni Mohamed,Tri-Tra-Raid Seraing,H,V1,26,01:14:39,Le Jogging Saint-Martin,2025-04-05,13.50,20250405NandrinGC.pdf,le jogging saint-martin_2025-04-05_13.5,V1
84596,105,Abdelmoumni Mohamed,Ser Athl,H,SEN,35,0:56:17,La Corrida D'Hermalle-Sous-Huy,2018-07-20,10.40,180720-HERMALLE-10400.pdf,la corrida d'hermalle-sous-huy_2018-07-20_10.4,SH
86945,24,Abdullahi Mohamed,,H,SE,13,0:53:04,Jogging Des Poudingues - Ombret,2010-10-16,12.47,2010 - ARCHIVE - OMBRET (12.47).pdf,jogging des poudingues - ombret_2010-10-16_12.47,SH
87235,159,Abdullani Mohamed,,H,SEH,50,0:59:15,Fraiture En Condroz,2011-05-13,11.80,2011 - CONDRUZIEN - FRAITURE (11.80).pdf,fraiture en condroz_2011-05-13_11.8,SH
92158,10,Abdelmoumni Mohamed,Ttrs Seraing,H,V1,3,00:42:13,La Corrida D'Hermalle-Sous-Huy,2024-07-19,10.20,240719-CONDRUSIEN-GOALTIMING-CORRIDA HERMALLE ...,la corrida d'hermalle-sous-huy_2024-07-19_10.2,V1
93222,8,Abdullahi Mohamed,,H,SEH,8,0:46:25,La Neupreenne,2012-03-18,12.00,2012-CONDRUSIEN-NEUPRE-11.98.pdf,la neupreenne_2012-03-18_12.0,SH
104162,33,Abdullani Mohamed,,H,SEH,14,0:53:37,A Pid Po L'Bwes - Fraiture En Condroz,2013-05-10,12.30,2013-CONDRUSIEN-FRAITURE1-12.30.pdf,a pid po l'bwes - fraiture en condroz_2013-05-...,SH
106636,5,Abdullani Mohamed,,H,SEH,5,00:43:26,Modave,2011-05-27,11.28,2011 - CONDRUZIEN - FRAITURE (11.30).pdf,modave_2011-05-27_11.28,SH

# Durée

In [85]:
import re

pattern = re.compile(
    r"^(\d{1,2}:\d{2}:\d{2}|\d{2}:\d{2}|\d{2}:\d{2}:\d{1})$"
)

invalides = df.loc[
    ~df["Temps"].astype(str).str.match(pattern, na=False),
    "Temps"
].unique()

print(invalides)

<ArrowStringArray>
['#VALEUR!',   '1:13:5', '0: 14:32', '0: 16:27', '0: 16:57', '0: 17:05',
 '0: 17:06', '0: 17:28', '0: 18:09', '0: 19:51', '0: 20:03', '0: 20:23',
 '0: 20:39', '0: 21:07', '0: 21:27', '0: 22:18', '0: 22:30', '0: 22:47',
 '0: 22:49', '0: 23:35', '0: 23:36', '0: 23:45', '0: 23:54', '0: 25:45',
 '0: 27:11', '0: 27:37', '0: 28:01', '0: 28:23', '0: 32:50', '0: 32:51',
 '0: 32:52', '0: 33:34']
Length: 32, dtype: str

In [86]:
df[df["Temps"] == "#VALEUR!"]

,Position,Nom,Club,Sexe,Categorie,Position Catégorie,Temps,NomCourse,Date,Distance,source_file,racekey,categorie_harmonisee
2262,200,Degrange Valerie,Run'Essence,F,DAM,17,#VALEUR!,Les Dreves De La Vecquee - Seraing,2018-09-07,9.7,180907-SERAING-9700.pdf,les dreves de la vecquee - seraing_2018-09-07_9.7,SD
32309,103,Carlino Tony,Neupre Ac,H,VE1,27,#VALEUR!,Le Jogging De La Saint-Nicolas - Marchin,2018-11-17,11.0,181117-MARCHIN-11000.pdf,le jogging de la saint-nicolas - marchin_2018-...,V1
32310,104,Behets Marc,,H,VE3,8,#VALEUR!,Le Jogging De La Saint-Nicolas - Marchin,2018-11-17,11.0,181117-MARCHIN-11000.pdf,le jogging de la saint-nicolas - marchin_2018-...,V3
75050,175,Collard Lucien,Chicken Run,H,VE3,12,#VALEUR!,Le Jogging Andre Servotte - Modave,2019-02-09,11.5,190209-LE JOGGING ANDRE SERVOTTE-MODAVE-11500.pdf,le jogging andre servotte - modave_2019-02-09_...,V3
75051,176,Ciccarese Thomas,Run'Essence,H,SEN,77,#VALEUR!,Le Jogging Andre Servotte - Modave,2019-02-09,11.5,190209-LE JOGGING ANDRE SERVOTTE-MODAVE-11500.pdf,le jogging andre servotte - modave_2019-02-09_...,SH
75052,177,Marechal Dimitri,,H,VE1,45,#VALEUR!,Le Jogging Andre Servotte - Modave,2019-02-09,11.5,190209-LE JOGGING ANDRE SERVOTTE-MODAVE-11500.pdf,le jogging andre servotte - modave_2019-02-09_...,V1
75054,179,Thiry Thomas Jose,,H,SEN,78,#VALEUR!,Le Jogging Andre Servotte - Modave,2019-02-09,11.5,190209-LE JOGGING ANDRE SERVOTTE-MODAVE-11500.pdf,le jogging andre servotte - modave_2019-02-09_...,SH

In [87]:
INVALID_VALUES = {
    "#VALEUR!"
}

def normalize_time(value):

    if pd.isna(value):
        return pd.NaT

    value = str(value).strip()

    # valeurs invalides connues
    if value in INVALID_VALUES:
        return pd.NaT

    # suppression espaces parasites
    value = value.replace(" ", "")

    parts = value.split(":")

    # format MM:SS
    if len(parts) == 2:
        mm, ss = parts
        hh = "00"

    # format HH:MM:SS
    elif len(parts) == 3:
        hh, mm, ss = parts

    else:
        return pd.NaT

    # padding
    hh = hh.zfill(2)
    mm = mm.zfill(2)
    ss = ss.zfill(2)

    normalized = f"{hh}:{mm}:{ss}"

    try:
        return pd.to_timedelta(normalized)
    except:
        return pd.NaT

In [88]:
df["temps_clean"] = df["Temps"].apply(normalize_time)

In [89]:
df = df[df["temps_clean"].notna()]

In [90]:
df["temps_sec"] = df["temps_clean"].dt.total_seconds().astype("int32")

In [91]:
df.head()

,Position,Nom,Club,Sexe,Categorie,Position Catégorie,Temps,NomCourse,Date,Distance,source_file,racekey,categorie_harmonisee,temps_clean,temps_sec
0,1,Simonet Yves,P8,H,SEN,1,0:39:48,La Neupreenne - Neupre,2017-03-12,11.0,170312-CONDRUSIEN-CHRONORACE-NEUPRE-11000.pdf,la neupreenne - neupre_2017-03-12_11.0,SH,0 days 00:39:48,2388
1,2,Honnay Xavier,,H,SEN,2,0:39:49,La Neupreenne - Neupre,2017-03-12,11.0,170312-CONDRUSIEN-CHRONORACE-NEUPRE-11000.pdf,la neupreenne - neupre_2017-03-12_11.0,SH,0 days 00:39:49,2389
2,3,Corswarem Pierre-Henri,Foulees Du Plai,H,SEN,3,0:39:53,La Neupreenne - Neupre,2017-03-12,11.0,170312-CONDRUSIEN-CHRONORACE-NEUPRE-11000.pdf,la neupreenne - neupre_2017-03-12_11.0,SH,0 days 00:39:53,2393
3,4,Grilo Carvalho Thomas,Foulees Du Plai,H,SEN,4,0:39:54,La Neupreenne - Neupre,2017-03-12,11.0,170312-CONDRUSIEN-CHRONORACE-NEUPRE-11000.pdf,la neupreenne - neupre_2017-03-12_11.0,SH,0 days 00:39:54,2394
4,5,Schmitz Bertrand,Foulees Du Plai,H,SEN,5,0:39:54,La Neupreenne - Neupre,2017-03-12,11.0,170312-CONDRUSIEN-CHRONORACE-NEUPRE-11000.pdf,la neupreenne - neupre_2017-03-12_11.0,SH,0 days 00:39:54,2394

In [92]:
df[df['Position Catégorie'].isin(['', '#REF!', '0', '-'])]

,Position,Nom,Club,Sexe,Categorie,Position Catégorie,Temps,NomCourse,Date,Distance,source_file,racekey,categorie_harmonisee,temps_clean,temps_sec
194,196,Nr 8718,,X,XXX,,0:58:55,La Neupreenne - Neupre,2017-03-12,11.0,170312-CONDRUSIEN-CHRONORACE-NEUPRE-11000.pdf,la neupreenne - neupre_2017-03-12_11.0,XXX,0 days 00:58:55,3535
457,459,Etienne Vincent,,X,XXX,,1:12:37,La Neupreenne - Neupre,2017-03-12,11.0,170312-CONDRUSIEN-CHRONORACE-NEUPRE-11000.pdf,la neupreenne - neupre_2017-03-12_11.0,XXX,0 days 01:12:37,4357
661,49,Heiwen Alain,,X,XXX,,0:28:04,Le Jogging De La Piscine - Ocquier,2018-06-22,5.5,180622-OCQUIER-5500.pdf,le jogging de la piscine - ocquier_2018-06-22_5.5,XXX,0 days 00:28:04,1684
2864,132,Inconnu Inconnu,,X,xxx,0,1:04:09,Les Sentiers Du Val - Seraing,2013-07-06,10.2,2013-CONDRUSIEN-SERAING-10.20.pdf,les sentiers du val - seraing_2013-07-06_10.2,XXX,0 days 01:04:09,3849
2954,20,Lemaire Philippe,,X,XXX,,0:24:25,Marche,2012-09-15,5.0,2012-CONDRUZIEN-MARCHE-5.00.pdf,marche_2012-09-15_5.0,XXX,0 days 00:24:25,1465
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113959,94,Loeckx Celine,,X,XXX,,0:32:10,Jogging Des 2 Provinces - Bois & Borsu,2015-05-22,5.2,2015-CONDRUSIEN-MODAVE-5.20.pdf,jogging des 2 provinces - bois & borsu_2015-05...,XXX,0 days 00:32:10,1930
114025,160,Renotte Arnaud,,X,XXX,,0:38:18,Jogging Des 2 Provinces - Bois & Borsu,2015-05-22,5.2,2015-CONDRUSIEN-MODAVE-5.20.pdf,jogging des 2 provinces - bois & borsu_2015-05...,XXX,0 days 00:38:18,2298
114044,179,Chleu Anna,,X,XXX,,0:46:07,Jogging Des 2 Provinces - Bois & Borsu,2015-05-22,5.2,2015-CONDRUSIEN-MODAVE-5.20.pdf,jogging des 2 provinces - bois & borsu_2015-05...,XXX,0 days 00:46:07,2767
114473,44,Maree Nadine,,X,XXX,,0:25:07,Les Tidges D'Havlondje - Havelange,2016-10-08,4.6,161008-CONDRUSIEN-HAVELANGE-4600.pdf,les tidges d'havlondje - havelange_2016-10-08_4.6,XXX,0 days 00:25:07,1507
114516,87,Chasseur Dominique,,X,XXX,,0:30:26,Les Tidges D'Havlondje - Havelange,2016-10-08,4.6,161008-CONDRUSIEN-HAVELANGE-4600.pdf,les tidges d'havlondje - havelange_2016-10-08_4.6,XXX,0 days 00:30:26,1826

Les positions de catégorie invalides concernent toujours les Catégories non définies (XXX) --> position à mettre à 0 pour toute la catégorie XXX

In [94]:
mask_xxx = df['categorie_harmonisee'] == "XXX"
df.loc[mask_xxx, 'Position Catégorie'] = '0'

In [95]:
cols = ["Position", "Position Catégorie"]

for col in cols:
    df[col] = (
        df[col]
        .astype("int")
    )

In [96]:
df.head()

,Position,Nom,Club,Sexe,Categorie,Position Catégorie,Temps,NomCourse,Date,Distance,source_file,racekey,categorie_harmonisee,temps_clean,temps_sec
0,1,Simonet Yves,P8,H,SEN,1,0:39:48,La Neupreenne - Neupre,2017-03-12,11.0,170312-CONDRUSIEN-CHRONORACE-NEUPRE-11000.pdf,la neupreenne - neupre_2017-03-12_11.0,SH,0 days 00:39:48,2388
1,2,Honnay Xavier,,H,SEN,2,0:39:49,La Neupreenne - Neupre,2017-03-12,11.0,170312-CONDRUSIEN-CHRONORACE-NEUPRE-11000.pdf,la neupreenne - neupre_2017-03-12_11.0,SH,0 days 00:39:49,2389
2,3,Corswarem Pierre-Henri,Foulees Du Plai,H,SEN,3,0:39:53,La Neupreenne - Neupre,2017-03-12,11.0,170312-CONDRUSIEN-CHRONORACE-NEUPRE-11000.pdf,la neupreenne - neupre_2017-03-12_11.0,SH,0 days 00:39:53,2393
3,4,Grilo Carvalho Thomas,Foulees Du Plai,H,SEN,4,0:39:54,La Neupreenne - Neupre,2017-03-12,11.0,170312-CONDRUSIEN-CHRONORACE-NEUPRE-11000.pdf,la neupreenne - neupre_2017-03-12_11.0,SH,0 days 00:39:54,2394
4,5,Schmitz Bertrand,Foulees Du Plai,H,SEN,5,0:39:54,La Neupreenne - Neupre,2017-03-12,11.0,170312-CONDRUSIEN-CHRONORACE-NEUPRE-11000.pdf,la neupreenne - neupre_2017-03-12_11.0,SH,0 days 00:39:54,2394